.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH TLSDATE 1 "OCTOBER 2012" Linux "User Manuals"
.SH NAME
tlsdate-routeup \- secure parasitic rdate replacement route change utility
.SH SYNOPSIS
.B tlsdate-routeup
.SH DESCRIPTION
.B tlsdate-routeup
is a tool for noticing network route status changes. It binds to AF_NETLINK and
prints 'n' followed by a CRLF for each route change.

This tool is designed to be run by tlsdated.
.SH BUGS
It's likely! Let us know by contacting jacob@appelbaum.net

Note that
.B tlsdate(1)
is still in Alpha, and may not work as expected.
.SH AUTHOR
Jacob Appelbaum <jacob at appelbaum dot net>
.SH "SEE ALSO"
.B tlsdate(1),
.B tlsdated(1)
.B tlsdate-helper(1)
.B tlsdate-dbus-announce(1)
