.TH clockspeed 1
.SH NAME
clockspeed \- speed up or slow down the local clock, continuously
.SH SYNOPSIS
.B clockspeed
.SH DESCRIPTION
.B clockspeed
resets the local UNIX clock every three seconds
according to
(1) an internal hardware tick counter and
(2) occasional real-time measurements from a reliable source.

.B clockspeed
reads the real-time measurements from
.BR /usr/local/clockspeed/adjust .
Each real-time measurement must be a single 16-byte packet,
expressed as a TAI64NA time adjustment to the local UNIX clock.

.B clockspeed
does not place any limits on the possible adjustments.
It is your responsibility to make sure that the measurements are reliable.

After two real-time measurements,
.B clockspeed
can figure out the number of real attoseconds per tick.
It saves this number in TAI64NA format in
.BR /usr/local/clockspeed/etc/atto ,
overwriting
.B /usr/local/clockspeed/etc/atto.tmp
for reliability.
It reads
.B /usr/local/clockspeed/etc/atto
when it starts up again.

.B clockspeed
must be run by
.BR root .
.SH "SEE ALSO"
clockadd(1),
clockview(1),
sntpclock(1),
taiclock(1),
adjtime(2),
gettimeofday(2)
