.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH TLSDATED 8 "OCTOBER 2012" Linux "User Manuals"
.SH NAME
tlsdated \- secure parasitic rdate replacement daemon
.SH SYNOPSIS
.B tlsdated [\-wprlsvh] \
[\-t <n>] \
[\-d <n>] \
[\-T <n>] \
[\-D <n>] \
[\-c /path/to ] \
[\-a seconds ] \
[\-\-] \
[commands to be passed to tlsdate]
.SH DESCRIPTION
.B tlsdated
is a daemon that runs tlsdate. It must be run as root or otherwise have the
proper caps; it will not be able to set the system time without running as root
or another privileged user.
.SH OPTIONS
.IP "\-w"
don't set hwclock
.IP "\-p"
dry run (don't really set time)
.IP "\-r"
use stdin instead of netlink for routes
.IP "\-t [n]"
try up to n times if unsuccessful to synchronize the time
.IP "\-d [n]"
delay n seconds between tries
.IP "\-T [n]"
give subprocess n chances to exit
.IP "\-D [n]"
delay n seconds between wait attempts
.IP "\-c [/path/to/cache/directory/]"
set the cache directory
.IP "\-a [n]"
run at most every n seconds in steady state
.IP "\-l"
don't load disk timestamps
.IP "\-s"
don't save disk timestamp
.IP "\-j [n]"
add up to n seconds of jitter to steady-state fetches
.IP "\-v"
be verbose
.IP "\-b"
be extra verbose (debugging)
.IP "\-U"
do not use DBus if supported
.IP "\-h"
print help message
.IP "\-f [/path/to/config/file]"
use alternate config file
.IP "\-x [proxy]"
override the proxy supplied to sources in the config file
.IP "[tlsdate command arguments]"
arguments to be passed to tlsdate at launch time

.SH BUGS
It's likely! Let us know by contacting jacob@appelbaum.net

Note that
.B tlsdate(8)
is in Beta, and may not work as expected.
.SH AUTHOR
Jacob Appelbaum <jacob at appelbaum dot net>
.SH "SEE ALSO"
.B tlsdate(1),
.B tlsdate-helper(1),
.B tlsdated.conf(5)
