.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH TLSDATE-DBUS-ANNOUNCE 1 "JANUARY 2013" Linux "User Manuals"
.SH NAME
tlsdate-dbus-announce \- secure parasitic rdate replacement dbus announcer
.SH SYNOPSIS
.B tlsdate-dbus-announce
.SH DESCRIPTION
.B tlsdate-dbus-announce
is a tool for use with tlsdated. It is automatically launched by tlsdated to
announce that the system time has changed.
.SH BUGS
It's likely! Let us know by contacting jacob@appelbaum.net

Note that
.B tlsdate(1)
is still in Alpha, and may not work as expected.
.SH AUTHOR
Jacob Appelbaum <jacob at appelbaum dot net>
.SH "SEE ALSO"
.B tlsdated(1),
.B tlsdate-helper(1)
.B tlsdate-routeup(1)
