#! /bin/sh

set -e

case "$1" in
	install|upgrade)
		dpkg-maintscript-helper mv_conffile \
			/etc/init.d/tlsdate /etc/init.d/tlsdated 0.0.7-1.3~ -- "$@"
		dpkg-maintscript-helper mv_conffile \
			/etc/default/tlsdate /etc/default/tlsdated 0.0.7-1.3~ -- "$@"
		;;
	*)
		;;
esac

#DEBHELPER#
