.TH clockview 1
.SH NAME
clockview \- view an adjustment to the local clock
.SH SYNOPSIS
.B clockview
.SH DESCRIPTION
.B clockview
reads a TAI64NA time adjustment.
It then prints the local UNIX clock
and the local UNIX clock plus that adjustment.

The adjustment must be a single 16-byte packet.

Both clocks are printed in ISO style
(with nanoseconds and attoseconds), in the local time zone,
using
.BR localtime .
Beware that many systems do not handle leap seconds correctly in
.BR localtime .
.SH "SEE ALSO"
clockspeed(1),
clockadd(1),
sntpclock(1),
taiclock(1),
gettimeofday(2),
localtime(3)
